version: 2

workflows:
  version: 2
  default:
    jobs:
      - ios

step-library:
  - &restore-cache
      restore_cache:
        keys:
          - source-v1-{{ .Branch }}-{{ .Revision }}
          - source-v1-{{ .Branch }}-
          - source-v1-

  - &save-cache
      save_cache:
        key: source-v1-{{ .Branch }}-{{ .Revision }}
        paths:
          - Carthage

  - &prepare
      run:
        name: Prepare
        command: |
          git submodule sync
          brew install carthage
          carthage bootstrap --platform ios --cache-builds --configuration Release --no-use-binaries

  - &build-test-MapboxCoreNavigation
      run:
        name: Build and test MapboxCoreNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme MapboxCoreNavigation clean build test | xcpretty

  - &build-MapboxNavigation
      run:
        name: Build MapboxNavigation
        command: |
          xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,id=9F32C487-FAEC-4ABE-B00D-159EC007E50D' -project MapboxNavigation.xcodeproj -scheme MapboxNavigation clean build | xcpretty

jobs:
  ios:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    # Need to invoke bash as a login shell so that chruby is called to upgrade Ruby
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      # Set Ruby version to workaround https://github.com/CocoaPods/CocoaPods/issues/7447
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4" > ~/.ruby-version
      - *prepare
      - *restore-cache
      - *build-test-MapboxCoreNavigation
      - *build-MapboxNavigation
      - *save-cache
